fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
  - repo: https://github.com/myint/docformatter
    rev: v1.7.1
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --close-quotes-on-newline]
        stages: [commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
        stages: [commit]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.4
    hooks:
      - id: pycln
        args: [-q, --all, --exclude, __init__.py]
        stages: [commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile black]
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [commit]
        args: [--experimental-string-processing]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
        stages: [commit]
        args: [--max-line-length, "88"]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
