- entry: docformatter
  args: [--in-place, --make-summary-multi-line, --close-quotes-on-newline, --wrap-summaries, "88"]
  pass_filenames: true
  files: '\.py'
- entry: ruff
  args: [check, --fix, .]
- id: ruff-format
  entry: ruff
  args: [format, .]
<<<<<<< HEAD
- entry: shfmt
  args: [ -w, -i, "4" ]
  pass_filenames: true
  files: '\.sh'
=======
>>>>>>> template
- id: infer-missing-annotations
  entry: python
  args: [-m, libcst.tool, codemod, autotyping.AutotypeCommand, --aggressive]
  pass_filenames: true
  files: '\.py'
- entry: mypy
  args: [.]
  fail_fast: true
  require_serial: true
- id: run-tests
  entry: coverage run
  fail_fast: true
<<<<<<< HEAD
=======
- entry: check-coverage
>>>>>>> template
- entry: check-shields
- entry: check-version
- entry: check-import
