- entry: ruff
  args: [check, --fix, .]
- id: ruff-format
  entry: ruff
  args: [format, .]
- entry: expand-docstrings
  files: '\.py'
- entry: shfmt
  args: [ -w, -i, "4" ]
  pass_filenames: true
  files: '\.sh'
- id: infer-missing-annotations
  entry: python
  args: [-m, libcst.tool, codemod, autotyping.AutotypeCommand, --aggressive]
  pass_filenames: true
  files: '\.py'
- entry: mypy
  args: [.]
  fail_fast: true
  require_serial: true
- entry: check-version
- entry: check-import
