name: Test end-to-end

on:
  workflow_dispatch:

jobs:
  test-end-to-end:
    name: Test end-to-end
    runs-on: ubuntu-latest
    steps:
      - name: Test end-to-end
        uses: docker://ubuntu:latest
        env:
          RCLONE: ${{ secrets.RCLONE }}
          USERNAME: quinten
        with:
          args: wget -O - https://raw.githubusercontent.com/quintenroets/sysetup/main/bin/setup | bash
