name: Build

on:
  workflow_dispatch:

jobs:
  test-end-to-end:
    name: Test end-to-end
    runs-on: ubuntu-latest
    steps:
      - name: Test end-to-end
        run: wget -O - https://raw.githubusercontent.com/quintenroets/sysetup/main/bin/setup | bash
        env:
          RCLONE: ${{ secrets.RCLONE }}
